// AUTO-GENERATED by scripts/extract-config-groups.mjs — do not edit by hand.
// Source: cdk/gateway.yaml
// Declared IdP groups from the gateway config, so the group-cap picker can
// suggest groups that have not generated any spend yet.
export const CONFIG_GROUPS = ["business","engineering","gateway-admins"]
